Vagrantfile
=> Revert "Remove Vagrant"

http/src/main/scala/com/paypal/cascade/http/resource/HttpResourceActor.scala
This reduces the maximum number of messages from four to three.
=> Eliminate one additional message

common/src/test/scala/com/paypal/cascade/common/tests/scalacheck/scalacheck.scala
See https://github.com/rickynils/scalacheck/issues/129.
=> Add suchThat size constraints to List and String generators

README.md
=> Clarify that you don't create a new account at oss.sonatype.org, you reuse the one from issues.

.travis.yml, project/Build.scala
Adds all of:
* OpenJDK 7
* Oracle JDK 7
* Oracle JDK 8
to the Travis build, to help track https://github.com/paypal/cascade/issues/80
=> add multiple jdks to travis build

.travis.yml, README.md, project/Build.scala, project/plugins.sbt
- Sets up scoverage
- Removes jacoco
- Adds support for publishing to Codacy
- Adds Codacy badge to readme
=> Scoverage and Codacy

common/src/main/scala/com/paypal/cascade/common/option/option.scala, common/src/main/scala/com/paypal/cascade/common/trys/trys.scala, common/src/test/scala/com/paypal/cascade/common/tests/option/OptionListSpecs.scala, common/src/test/scala/com/paypal/cascade/common/tests/trys/TrysSpecs.scala
- Adds implicit class for `List[Option[T]]` to allow `.sequence`. Includes tests
- Adds missing test for the `OptionList` class.
- Adds fairly specific sequencing methods for `Try`s
=> Adds option and try sequencing

README.md, Readme-Template.md, doc/HTTP_RESOURCE_GETTING_STARTED.md
1. Fixed a link in HTTP_RESOURCE_GETTING_STARTED.md
2. Fixed scala version in README.md
3. Made sure the Readme-Template.md had the codacy badge in it.
=> Fix a few things in the readmes

project/Build.scala
=> Bump SLF4J to 1.7.10

common/src/main/scala/com/paypal/cascade/common/future/future.scala, common/src/main/scala/com/paypal/cascade/common/option/option.scala, common/src/test/scala/com/paypal/cascade/common/tests/future/FutureSpecs.scala, common/src/test/scala/com/paypal/cascade/common/tests/option/RichOptionSpecs.scala
```
val option = Option(7)
option.toFuture
val future = Future(7)
future.mapFailure(new Exception("foo"))
```
=> Add f.mapFailure(new CustomException); Add option.toFuture (without throwable)

common/src/test/scala/com/paypal/cascade/common/tests/future/FutureSpecs.scala, common/src/test/scala/com/paypal/cascade/common/tests/option/RichOptionSpecs.scala, common/src/test/scala/com/paypal/cascade/common/tests/util/NoConcurrentExecutionContext.scala, http/src/test/scala/com/paypal/cascade/http/tests/resource/HttpResourceActorSpecs.scala, http/src/test/scala/com/paypal/cascade/http/tests/resource/ResourceSpecs.scala, project/Build.scala
Reverts paypal/cascade#116
We're going to hold off on this merge for a few weeks.
=> Revert "Upgrade specs2 to 3.1"

project/Build.scala
- Adds a deadlock fix in jackson
=> Upgrading to Jackson 2.4.4

http/src/main/scala/com/paypal/cascade/http/resource/HttpResourceActor.scala, project/Build.scala
=> Fix a few Codacy warnings

http/src/main/scala/com/paypal/cascade/http/actor/SprayActor.scala
This resolves a few Codacy warnings.
=> Cleanup Scopes

http/src/main/scala/com/paypal/cascade/http/actor/SprayActor.scala, http/src/main/scala/com/paypal/cascade/http/resource/ResourceService.scala, http/src/main/scala/com/paypal/cascade/http/server/CascadeRejectionHandler.scala, http/src/main/scala/com/paypal/cascade/http/server/SprayConfiguration.scala, http/src/test/scala/com/paypal/cascade/http/tests/actor/SprayActorSpecs.scala, http/src/test/scala/com/paypal/cascade/http/tests/api/SprayRoutingServer.scala
=> override 'query param missing' error code

README.md
=> Remove mention of components

.travis.yml, project/Build.scala
=> Drop 2.10 support

README.md, Readme-Template.md
The final thing to add before we release 0.5!
=> Releasing does not involve invoking cross anymore

http/src/main/scala/com/paypal/cascade/http/resource/HttpResourceActor.scala
https://github.com/paypal/cascade/issues/86
=> Allow for any rather than anyref in request parser

json/src/test/scala/com/paypal/cascade/json/tests/JsonUtilSpecs.scala
Added to the Maps object a check for case sensitive keys
=> Added a test for case sensitive keys

doc/HTTP_RESOURCE_GETTING_STARTED.md, examples/src/main/scala/com/paypal/cascade/examples/http/resource/MyHttpServer.scala, http/src/main/scala/com/paypal/cascade/http/actor/SprayActor.scala, http/src/main/scala/com/paypal/cascade/http/server/SprayConfiguration.scala, http/src/test/scala/com/paypal/cascade/http/tests/actor/SprayActorSpecs.scala, http/src/test/scala/com/paypal/cascade/http/tests/resource/ResourceServiceSpecs.scala
=> Add `interface` to `SprayConfiguration` to allow custom bind interface.
